title: "Ho Nguyen"
description: "QA Engineer • Automation • Testing Strategy"
baseurl: ""
url: "https://nlongho.github.io"

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Ho Nguyen"
  email: "your-email@example.com"
